### ISSUE TITLE
Week2

### ISSUE THREAD

**Issue by SaschaVanEssen** [TPLxxA/project#2]
Zet bovenaan je README.md een link naar je GitHub Pages site. Je process book mag af en toe wat uitgebreider, met (kort) waar je tegenaan gelopen bent en de belangrijke beslissingen die je genomen hebt. PROCESSBOOK.md moet PROCESS.md heten

**Comment by TPLxxA** [comment]
- Github pages aangemaakt + bovenaan readme gezet.
- PROCESSBOOK.md naam veranderd naar PROCESS.md
- Process book zal ik wat uitgebreider maken voortaan
